# Generated by Django 4.0.4 on 2022-06-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='sub',
        ),
    ]
