# Generated by Django 4.0.4 on 2022-06-29 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_remove_contact_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('Dues', models.CharField(default='0', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Name', models.CharField(max_length=100)),
                ('fathers_Name', models.CharField(max_length=100)),
                ('Email_id', models.CharField(max_length=100)),
                ('Classes', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
